#:schema https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: YOUR_GITHUB_USER/YOUR_REPOSITORY

media_folder: /public/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: /src/content/pages
    format: yaml
    fields:
      - name: title
        label: Section title
        widget: string

      - name: image
        widget: object
        fields:
          - { name: src, widget: image }
          - { name: alt, widget: string }

      - name: scroller
        label: Scroller
        widget: relation
        collection: scrollers
        value_field: scroller_id
        display_fields: [title]
        search_fields: [title]
        
      - name: content
        label: Content
        widget: richtext